project_id = "vomymtttacomieswsomg"

[functions.generate-blog]
verify_jwt = false

[functions.refine-content]
verify_jwt = false

[functions.generate-title]
verify_jwt = false

[functions.publish-to-wordpress]
verify_jwt = false
